### ISSUE TITLE
Connection closes after "n"-encrypted messages

### ISSUE THREAD

**Issue by codmpm** [alladdin/node-lox-ws-api#9]
Over at the loxforum we've discovered a bug (maybe?).

If you use AES command enryption and send four to five commands in a row over the websocket, the connection get's closed. This won't happen if you do not use command encryption or send a webservice command oder the websocket.

Is this a bug in node-lox-ws-api or some kind of throttling from the miniserver side?

To reproduce simple send "Pulse" to a switch module in short intervals.

**Comment by alladdin** [comment]
It's fixed in version 0.2.8

**Comment by codmpm** [comment]
I will test as soon as I can and will get back to you.

**Comment by codmpm** [comment]
On a short test after updating to `0.2.8` I still have the problem.

**Comment by alladdin** [comment]
The problem may be in miniserver version. I have latest 8.3.3.21

The main problem is with salt in encryption. There is difference between Loxone 8.0 communication spec and 8.1

8.0:
12. Generate a random base64 salt -> {salt}

8.1:
12. Generate a random salt, hex string (length may vary, e.g. 2 bytes) -> {salt}

**Comment by codmpm** [comment]
I've tested it also with 8.3.x...

**Comment by codmpm** [comment]
Seems to work with node-lox-ws-api 0.3.1 👍
